config/routes.rb
Rails.application.routes.draw do
  root    'static_pages#home'
  get     '/help',        		                     to: 'static_pages#help'
  get     '/about',       		                     to: 'static_pages#about'
  get     '/contact',     		                     to: 'static_pages#contact'
  get     '/signup',      		                     to: 'users#new'
  get     '/login',       		                     to: 'sessions#new'
  delete  '/logout',      		                     to: 'sessions#destroy'
  get     '/records',    		                       to: 'records#exes',        				     as: 'records'
  get     '/products',                             to: 'products#product_options',         as: 'products'
  get     '/categories',                           to: 'categories#category_options',      as: 'categories'
  get     '/stats',                                to: 'stats#show_stats',                 as: 'stats'
  delete  '/records/:record_id/destroy',           to: 'records#destroy',                  as: 'destroy_record'
  get     '/records/:record_id/edit',             to: 'records#edit',                     as: 'edit_record'
  get     '/records/new',                          to: 'records#new',                     as: 'new_record'
  post     '/products/create',                     to: 'products#create',                     as: 'create_product'




  # post     '/users/:user_id',                     to: 'users#update',                       as: 'update_user'
 # post     '/records/new',                          to: 'records#new',        			       as: 'new_record'
  post  '/users/:id(.:format)',                     to: 'users#edit'
  post '/records/:record_id/update',                to: 'records#update',                  as: 'update_record'
  post   '/login',                                  to: 'sessions#create'
  post    '/records',                               to: 'records#create',                  as: 'create_record'
  
  resources :users
end



# root GET    /                                     static_pages#home
#           help GET    /help(.:format)                       static_pages#help
#          about GET    /about(.:format)                      static_pages#about
#        contact GET    /contact(.:format)                    static_pages#contact
#         signup GET    /signup(.:format)                     users#new
#          login GET    /login(.:format)                      sessions#new
#         logout DELETE /logout(.:format)                     sessions#destroy
#        records GET    /records(.:format)                    records#exes
#     new_record GET    /records/new(.:format)                records#new
#       products GET    /products(.:format)                   products#product_options
#     categories GET    /categories(.:format)                 categories#category_options
#          stats GET    /stats(.:format)                      stats#show_stats
#    edit_record GET    /records/:record_id/edit(.:format)    records#edit
# destroy_record DELETE /records/:record_id/destroy(.:format) records#destroy
#  update_record POST   /records/:record_id/update(.:format)  records#update
#                POST   /login(.:format)                      sessions#create
#  create_record POST   /records(.:format)                    records#create
#          users GET    /users(.:format)                      users#index
#                POST   /users(.:format)                      users#create
#       new_user GET    /users/new(.:format)                  users#new
#      edit_user GET    /users/:id/edit(.:format)             users#edit
#           user GET    /users/:id(.:format)                  users#show
#                PATCH  /users/:id(.:format)                  users#update
#                PUT    /users/:id(.:format)                  users#update
#                DELETE /users/:id(.:format)                  users#destroy

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :oceans
  has_many :boats, through: :oceans
  has_many :records
  # el has_many lo que crea es un metodo para crear un array de los records que estan relacionados con un user
  # para ver los records de un user sol tienes que llamar al metodo records (user.records)
  # para relacionar un nuevo record con un user es como si le metieras a un array un record nuevo 
  # user.records << record



  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
 # Returns the hash digest of the given string.
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end


  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end


  def forget
    update_attribute(:remember_digest, nil)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    p "´" * 50
    p "edit"
    @user = User.find(params[:id])
  end

  def update
    p "_" * 50
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end



    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      p "-" * 50
      p current_user
      p @user
      redirect_to(root_url) unless current_user?(@user) || current_user.admin == true
      flash[:danger] = "I'm sorry, You are not allowed to do this." unless current_user?(@user) || current_user.admin == true 
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_profile.html.erb
<% if @user %>
<%= @user.name %>
<% end %>
<% provide(:title, @user.name) %>
<br><br>
<figure>
	<div class="row">
	  <div class="col-md-3">
	  	<%= link_to image_tag("add_icon.png", size: "150x150", alt: "Gasto"), 	records_path %>
	  	<h4 id="gastos"> GASTOS </h4>
	</div>
	
	<div class="row">
	  <div class="col-md-3">
	  	<%= link_to image_tag("product_icon.jpg", size: "150x150", alt: "Product") %>
	  	<h4 id="productos"> PRODUCTOS </h4>
	</div>
	
	<div class="row">
	  <div class="col-md-3">
	  	<%= link_to image_tag("box_icon.png", size: "150x150", alt: "Category")  %>
	  	<h4 id="categorias"> CATEGORÍAS </h4>
	</div>
	
	<div class="row">
	  <div class="col-md-3">
	  	<%= link_to image_tag("stats_icon.png", size: "150x150", alt: "Stats"), 	stats_path %>
	  	<h4 id="stats"> ESTADÍSTICAS </h4>
	</div>
</figure>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
   |  <%= link_to "Edit", user, method: :edit %>
   |  <%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
     
  <% end %>
</li>




                       

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>

<h1>Update profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<%= render 'profile' %>

app/views/users/user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>