config/routes.rb
Rails.application.routes.draw do
  root    'static_pages#home'
  get     '/help',        		                     to: 'static_pages#help'
  get     '/about',       		                     to: 'static_pages#about'
  get     '/contact',     		                     to: 'static_pages#contact'
  get     '/signup',      		                     to: 'users#new'
  get     '/login',       		                     to: 'sessions#new'
  delete  '/logout',      		                     to: 'sessions#destroy'
  get     '/records',    		                       to: 'records#exes',        				     as: 'records'
  get     '/products',                             to: 'products#product_options',         as: 'products'
  get     '/categories',                           to: 'categories#category_options',      as: 'categories'
  get     '/stats',                                to: 'stats#show_stats',                 as: 'stats'
  delete  '/records/:record_id/destroy',           to: 'records#destroy',                  as: 'destroy_record'
  get     '/records/:record_id/edit',             to: 'records#edit',                     as: 'edit_record'
  get     '/records/new',                          to: 'records#new',                     as: 'new_record'
  post     '/products/create',                     to: 'products#create',                     as: 'create_product'




  # post     '/users/:user_id',                     to: 'users#update',                       as: 'update_user'
 # post     '/records/new',                          to: 'records#new',        			       as: 'new_record'
  post  '/users/:id(.:format)',                     to: 'users#edit'
  post '/records/:record_id/update',                to: 'records#update',                  as: 'update_record'
  post   '/login',                                  to: 'sessions#create'
  post    '/records',                               to: 'records#create',                  as: 'create_record'
  
  resources :users
end



# root GET    /                                     static_pages#home
#           help GET    /help(.:format)                       static_pages#help
#          about GET    /about(.:format)                      static_pages#about
#        contact GET    /contact(.:format)                    static_pages#contact
#         signup GET    /signup(.:format)                     users#new
#          login GET    /login(.:format)                      sessions#new
#         logout DELETE /logout(.:format)                     sessions#destroy
#        records GET    /records(.:format)                    records#exes
#     new_record GET    /records/new(.:format)                records#new
#       products GET    /products(.:format)                   products#product_options
#     categories GET    /categories(.:format)                 categories#category_options
#          stats GET    /stats(.:format)                      stats#show_stats
#    edit_record GET    /records/:record_id/edit(.:format)    records#edit
# destroy_record DELETE /records/:record_id/destroy(.:format) records#destroy
#  update_record POST   /records/:record_id/update(.:format)  records#update
#                POST   /login(.:format)                      sessions#create
#  create_record POST   /records(.:format)                    records#create
#          users GET    /users(.:format)                      users#index
#                POST   /users(.:format)                      users#create
#       new_user GET    /users/new(.:format)                  users#new
#      edit_user GET    /users/:id/edit(.:format)             users#edit
#           user GET    /users/:id(.:format)                  users#show
#                PATCH  /users/:id(.:format)                  users#update
#                PUT    /users/:id(.:format)                  users#update
#                DELETE /users/:id(.:format)                  users#destroy

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :user
	belongs_to :boat
	belongs_to :product
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	def exes
		p "EXES" * 20
		p @exes = Record.all
		 @products = Product.all

	end

	def new
		p "NEW" * 50
		@record = Record.new
		@categories = Category.all

	end

	def create
	  p "C" * 20
	  p "create"	  
	  # "calendar"=>{"fecha(1i)"=>"2017", "fecha(2i)"=>"10", "fecha(3i)"=>"21"}, 
	  # "category"=>{"product_id"=>"1"}, 
	  # "record"=>{"account"=>"amount", 
	  # 			"note"=>"note"}, 
	  # "commit"=>"Save", 
	  # "controller"=>"records", 
	  # "action"=>"create"

	  # Aquí el error me marcaba NoMethodError in RecordsController#create undefined method 'id' for nil:NilClass.
	  # Lo que hice fue cambiar:
	  # boat = current_user.boats
	  # boat_id = boat[0].id
	  # Por las siguientes dos líneas de abajo, siendo que como ahorita solo existe un boat (1), no es necesario buscar el boat del current_user, porque todos tienen el mismo. 
	  boat = Boat.find(1)
	  boat_id = boat.id
	  # <%=date_select(:calendar, :fecha)%> Los Params buscan dentro de calendar cada una de las variables de fecha (año, mes y día), representados en el formato de string "fecha(1i)"etc.
	  product = params[:category][:product_id]
	  if product == ""
	  	p "-" * 50
	  	flash[:danger] = "Por favor escoge un producto"
	  	redirect_to new_record_path
	  else 
	   año = params[:calendar]["fecha(1i)"]
	   mes = params[:calendar]["fecha(2i)"]
	   dia = params[:calendar]["fecha(3i)"]
	  # Aquí es necesario buscar products en donde están: en categories.  
	  gasto = params[:record][:account]
	  if gasto == ""
	  	gasto = 0.0
	  end
	  note = params[:record][:note]

	  p product
	  p @record = Record.create!(user_id: current_user.id, boat_id: boat_id, product_id: product, fecha: Time.gm(año, mes, dia), account: gasto, note: note)
	  
	  p current_user
	  p params
	  
	  redirect_to records_path
	  end

	end


	def edit
		p "Edit" * 50
         @record = Record.find(params[:record_id])
        # Hacía falta definir @categories en este método, ya que de otra forma no lo reconocía desde el group_select de la vista edit.
         @categories = Category.all
    end

    def update
    	  "UP" * 50
         @record = Record.find(params[:record_id])

        año = params[:calendar]["fecha(1i)"]
		mes = params[:calendar]["fecha(2i)"]
		dia = params[:calendar]["fecha(3i)"]
		# Actualizo la fecha antes de utilizar el método private de record_params, porque no encontré el formato datetime de "fecha".   
        @record.update(fecha: Time.gm(año, mes, dia), product_id: params[:category][:product_id])
        # p "XXXXX" *50
        # p params
        if @record.update(record_params)
        	flash[:success] = "Updated Succesfully"
        	redirect_to records_path
        else
            render 'edit'
        end

    end

    def destroy
    	p "DESTROY" * 50
    	Record.find(params[:record_id]).destroy
    	flash[:success] = "Exe deleted"
    	redirect_to records_path
    end	




	private
	
	    def record_params
	        params.require(:record).permit([:boat_id, :product_id, :fecha, :account, :note])
	    end


end	

app/views/records/edit.html.erb
<% provide(:title, 'Editar Gasto') %>
<% provide(:button_text, 'Guardar') %>
<h3>Editar Gasto</h3>

<%= form_for @record, url: update_record_path(@record), :method => :POST do |f| %>
     <p>
<!-- Cambié el f.select con el array de meses, por date_select  -->
     <%=date_select(:calendar, :fecha, selected: @record.fecha)%>

     <!-- Aquí le puse grouped collection: group_method - The name of a method which, when called on a member of collection, returns an array of child objects representing the <option> tags. Y le quité el dropdown de productos anterior: (quitar espacio en piquitos para que funcione erb):
     < %=f.collection_select :product_id, Product.order(:name),:id,:name, include_blank: false %> -->
	<%= grouped_collection_select(:category, :product_id, @categories, :products, :name, :id, :name, { :selected => [@record.product.category, @record.product_id]}) %>

	<p>Amount:</p>
   	<%= f.text_field :account, class: "input" %>
   	<p>Add a Note:</p>
   	<%= f.text_field :note, class: "input" %>
	<%= f.hidden_field :boat_id, :value => @record.boat_id %>





 </p>
 <p>
   <%= f.submit "Save", class: "button is-success is-large" %>
 </p>
<% end %>

app/views/records/exes.html.erb
<div class="block">
    <%= link_to "Añadir Nuevo Gasto", new_record_path, class: "btn btn-large btn-warning" %>
</div>

<% if @exes %>
	<h1>Lista de Gastos</h1>
	<div class="row">
	<table class="table table-striped">
	 <tr class="something">
	   <th id="tabletitle1" class="col-md-2">USER</th>
	   <th id="tabletitle1" class="col-md-2">PRODUCT</th>
	   <th id="tabletitle2" class="col-md-2">Y / M / D</th>
	   <th id="tabletitle3" class="col-md-2">AMOUNT</th>
	   <th id="tabletitle3" class="col-md-4">NOTES</th>
	   <th colspan="6"></th>
	 </tr>
	 <% @exes.each do |exe| %>
	   <tr>
	     <td><%= exe.user.name %></td>
	     <td><%= @products.find(exe.product_id).name %></td>
	     <!-- Aquí le agregué month y day y year, dividiendo en 3 partes esta sección, para poder tener los datos completos del seed -->
	     <!-- Aquí esto va a tener problemas si la clase de fecha es nil -->
	     <td><%= exe.fecha.year %> / <%= exe.fecha.month %> / <%= exe.fecha.day %></td>
	     <td><%= exe.account %></td>
	     <td><%= exe.note %></td></td>
	    
	     <td><%= link_to 'Edit', edit_record_path(exe), class: 'btn btn-primary' %></td>
	     <td><%= button_to 'Destroy', destroy_record_path(exe), class: 'btn btn-danger', method: :delete,
                                  data: { confirm: "You sure?" } %></td>
	   </tr>
	 <% end %>
	</table>
	</div>
<% end %>

app/views/records/new.html.erb
<% provide(:title, 'Nuevo Gasto') %>
<h3>Nuevo Gasto</h3>

<%= form_for @record, url: create_record_path, :method => :POST do |f| %>
     <p>
     
    <%=date_select(:calendar, :fecha)%>
	  
    <!-- Aquí le puse grouped collection: group_method - The name of a method which, when called on a member of collection, returns an array of child objects representing the <option> tags. Y le quité el dropdown de productos anterior: (quitar espacio en piquitos para que funcione erb):
     < %=f.collection_select :product_id, Product.order(:name),:id,:name, include_blank: false %> -->

  <div id="collection_input_div" >
	   <%= grouped_collection_select(:category, :product_id, @categories, :products, :name, :id, :name, prompt: "Escoge un Producto...", include_blank: false) %>    
    <!-- Trigger the modal with a button -->
  </div>
  <button type="button" class="btn btn-large btn-info" data-toggle="modal" data-target="#myModal">Añadir Nuevo Producto</button>


	<p>Amount:</p>
   	<%= f.text_field :account, class: "input" %>
   	<p>Add a Note:</p>
   	<%= f.text_field :note, class: "input" %>

 </p>
 <p>
   <%= f.submit "Save", class: "button is-success is-large" %>
 </p>
<% end %>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        
            <div class="row">
              <%= form_tag(create_product_path, :method => "post", :remote => true, :class => "navbar-form") do %>
              
              <div class="col-md-5 col-md-offset-2">
                <%= text_field_tag "category", nil, :placeholder => "Nueva Categoria", :class => "form-control" %>
              </div>

              <div class="col-md-5 col-md-offset-2">
                <%= text_field_tag "product", nil, :placeholder => "Nuevo Producto", :class => "form-control" %>
              </div>

              <div class="col-md-2">
                <%= submit_tag "Crear", :class => "btn btn-sm btn-primary"  %>
              </div>
              <% end %>
            </div>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>