config/routes.rb
Rails.application.routes.draw do
  root    'static_pages#home'
  get     '/help',        		                     to: 'static_pages#help'
  get     '/about',       		                     to: 'static_pages#about'
  get     '/contact',     		                     to: 'static_pages#contact'
  get     '/signup',      		                     to: 'users#new'
  get     '/login',       		                     to: 'sessions#new'
  delete  '/logout',      		                     to: 'sessions#destroy'
  get     '/records',    		                       to: 'records#exes',        				     as: 'records'
  get     '/products',                             to: 'products#product_options',         as: 'products'
  get     '/categories',                           to: 'categories#category_options',      as: 'categories'
  get     '/stats',                                to: 'stats#show_stats',                 as: 'stats'
  delete  '/records/:record_id/destroy',           to: 'records#destroy',                  as: 'destroy_record'
  get     '/records/:record_id/edit',             to: 'records#edit',                     as: 'edit_record'
  get     '/records/new',                          to: 'records#new',                     as: 'new_record'
  post     '/products/create',                     to: 'products#create',                     as: 'create_product'




  # post     '/users/:user_id',                     to: 'users#update',                       as: 'update_user'
 # post     '/records/new',                          to: 'records#new',        			       as: 'new_record'
  post  '/users/:id(.:format)',                     to: 'users#edit'
  post '/records/:record_id/update',                to: 'records#update',                  as: 'update_record'
  post   '/login',                                  to: 'sessions#create'
  post    '/records',                               to: 'records#create',                  as: 'create_record'
  
  resources :users
end



# root GET    /                                     static_pages#home
#           help GET    /help(.:format)                       static_pages#help
#          about GET    /about(.:format)                      static_pages#about
#        contact GET    /contact(.:format)                    static_pages#contact
#         signup GET    /signup(.:format)                     users#new
#          login GET    /login(.:format)                      sessions#new
#         logout DELETE /logout(.:format)                     sessions#destroy
#        records GET    /records(.:format)                    records#exes
#     new_record GET    /records/new(.:format)                records#new
#       products GET    /products(.:format)                   products#product_options
#     categories GET    /categories(.:format)                 categories#category_options
#          stats GET    /stats(.:format)                      stats#show_stats
#    edit_record GET    /records/:record_id/edit(.:format)    records#edit
# destroy_record DELETE /records/:record_id/destroy(.:format) records#destroy
#  update_record POST   /records/:record_id/update(.:format)  records#update
#                POST   /login(.:format)                      sessions#create
#  create_record POST   /records(.:format)                    records#create
#          users GET    /users(.:format)                      users#index
#                POST   /users(.:format)                      users#create
#       new_user GET    /users/new(.:format)                  users#new
#      edit_user GET    /users/:id/edit(.:format)             users#edit
#           user GET    /users/:id(.:format)                  users#show
#                PATCH  /users/:id(.:format)                  users#update
#                PUT    /users/:id(.:format)                  users#update
#                DELETE /users/:id(.:format)                  users#destroy

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    | <a href="http://www.railstutorial.org/">El Bote App | For roommates</a>
    by <a href="http://www.michaelhartl.com/">Carla Herrán</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "El Bote App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <!-- Esto es para que no aparezca el botón de Home una vez que ya iniciaste sesión. -->

        <% if logged_in? == false %>
          <li><%= link_to "Home", root_path %></li>
        <% end %>


        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
<!--     <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" -->   

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>